tasks:
  - name: Setup Remote App
    init: |
      bun install
      echo "ALCHEMY_PASSWORD=demo-password" > .env
      echo "Demo environment ready! Run 'bun run dev' to start."
    command: |
      echo "🚀 Remote App Template Ready!"
      echo "1. Set your ALCHEMY_PASSWORD in .env"
      echo "2. Run: bun run dev"
      echo "3. Open the preview to see your app"

ports:
  - port: 5173
    onOpen: open-preview
    name: SvelteKit Dev Server
  - port: 1337
    onOpen: ignore
    name: Worker Dev Server

vscode:
  extensions:
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss
